# Generated by Django 5.2.4 on 2025-08-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cover_image',
            new_name='image',
        ),
    ]
